raft: grow the inflights buffer instead of preallocating
Grow the inflights buffer as needed instead of preallocating it to its
max size. This avoids preallocating a lot of unnecessary
space (8*MaxInflightMsgs) when using lots of raft groups while still
allowing for a reasonable MaxInflightMsgs configuration.

raft: add tests for IsLocalMsg (#6357)

* raft: add tests for IsLocalMsg

* report index of failed tests

corrected the package name in logger

etcdctlv3: Readme.md updated

1. Under PUT example the put command was mentioned in capital which will
give the below error:
Error: unknown command "PUT" for "etcdctl"
Hence corrected the same.
2. The lease id is mentioned with 0x to denote hex but since its an
example, copy pasting the command will give the below error:
Error: bad lease ID (strconv.ParseInt: parsing "0x1234abcd": invalid
syntax), expecting ID in Hex
Hence modified the same to a sample correct value so that a user new to
etcd does not get confused.
3. The command ./etcdctl range foo does not work and gives the below
error:
Error: unknown command "range" for "etcdctl"
Hence corrected the same

clientv3: drain buffered WatchResponses before resuming

Otherwise, the watcherStream can receive WatchResponses in the
middle of a resume, corrupting the stream.

Fixes #6364

etcdctl: Corrected command in Readme.md (#6376)

Corrected command in Readme.md

grpcproxy: handle overloaded stream

grpcproxy: fix a data race

clientv3: use correct context in toErr (lease)

clientv3: drain buffered WatchResponses before resuming

Otherwise, the watcherStream can receive WatchResponses in the
middle of a resume, corrupting the stream.

Fixes #6364

etcdctl: Corrected command in Readme.md (#6376)

Corrected command in Readme.md

grpcproxy: handle overloaded stream

grpcproxy: fix a data race

clientv3: use correct context in toErr (lease)

etcdctl v3: Not able to verify transaction example via CMD fixed

Fixed : Not able to verify transaction example via CMD

ctlv3: fix line parsing for Windows

ctlv3: fix line parsing for Windows

ctlv3: fix line parsing for Windows

ctlv3: fix line parsing for Windows